openapi: 3.0.0
info:
  title: m-comics-store-users
  version: 1.0.0
servers:
  - url: http://localhost
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: CatFacts
paths:
  /v1/users/:
    get:
      tags:
        - Endpoint
      summary: Retrieve Model
      security:
        - noauthAuth: []
      parameters:
        - "username": "jorgemm13",
        - "first_name": "Jorge",
        - "last_name": "Mojica",
        - "age": 34,
        - "phone": 2292706733,
        - "email": "jorge.morfinez.m@gmail.com",
        - "password": "jorgemm13081054"
          in: body
          schema:
            type: integer
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: model
          content:
            application/json:
              schema:
                type: object
        '400':
          description: BAD REQUEST
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: object
        '405':
          description: METHOD NOT ALLOWED
          headers:
            Content-Type:
              schema:
                type: string
                example: text/html; charset=utf-8
            Allow:
              schema:
                type: string
                example: OPTIONS, POST
            Content-Length:
              schema:
                type: integer
                example: '178'
          content:
            text/plain:
              schema:
                type: string
              example: |-
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
                <title>405 Method Not Allowed</title>
                <h1>Method Not Allowed</h1>
                <p>The method is not allowed for the requested URL.</p>
/v1/users/login/:
    get:
      tags:
        - Endpoint
      summary: Retrieve Model
      security:
        - noauthAuth: []
      parameters:
        - username: str
          in: query
          schema:
            type: string
          example: 'jorgemm'
        - password: str
            in: query
            schema:
              type: string
            example: 'jorgemm1345634'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: model
          content:
            application/json:
              schema:
                type: object
        '400':
          description: BAD REQUEST
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: object
        '405':
          description: METHOD NOT ALLOWED
          headers:
            Content-Type:
              schema:
                type: string
                example: text/html; charset=utf-8
            Allow:
              schema:
                type: string
                example: OPTIONS, POST
            Content-Length:
              schema:
                type: integer
                example: '178'
          content:
            text/plain:
              schema:
                type: string
              example: |-
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
                <title>405 Method Not Allowed</title>
                <h1>Method Not Allowed</h1>
                <p>The method is not allowed for the requested URL.</p>
